export default [
    {code: '', title: 'Цинк, без покрытия', class: '', bgColor: '', textColor: '', groups: []},
    {code: 'ral1014', title: 'RAL 1014 Слоновая кость', class: 'ral1014', bgColor: '#ded09f', textColor: '', groups: ['Светлый', 'Желтый']},
    {code: 'ral1018', title: 'RAL 1018 Цинково-желтый', class: 'ral1018', bgColor: '#f3e03b', textColor: '', groups: ['Светлый', 'Желтый']},
    {code: 'ral2004', title: 'RAL 2004 Оранжевый', class: 'ral2004', bgColor: '#d35f23', textColor: 'white', groups: ['Оранжевый']},
    {code: 'ral3005', title: 'RAL 3005 Винно-красный', class: 'ral3005', bgColor: '#5e2028', textColor: 'white', groups: ['Темный', 'Красный']},
    {code: 'ral3009', title: 'RAL 3009 Оксид красный', class: 'ral3009', bgColor: '#703731', textColor: 'white', groups: ['Темный', 'Красный']},
    {code: 'ral3011', title: 'RAL 3011 Коричнево-красный', class: 'ral3011', bgColor: '#7e292c', textColor: 'white', groups: ['Темный', 'Красный', 'Коричневый']},
    {code: 'ral3020', title: 'RAL 3020 Транспортный красный', class: 'ral3020', bgColor: '#c1121c', textColor: 'white', groups: ['Темный', 'Красный']},
    {code: 'ral5002', title: 'RAL 5002 Ультрамарин', class: 'ral5002', bgColor: '#2b2c7c', textColor: 'white', groups: ['Темный', 'Синий']},
    {code: 'ral5005', title: 'RAL 5005 Сигнальный синий', class: 'ral5005', bgColor: '#154889', textColor: 'white', groups: ['Темный', 'Синий']},
    {code: 'ral6002', title: 'RAL 6002 Лиственно-зеленый', class: 'ral6002', bgColor: '#276235', textColor: 'white', groups: ['Темный', 'Зеленый']},
    {code: 'ral6005', title: 'RAL 6005 Зелёный мох', class: 'ral6005', bgColor: '#0f4336', textColor: 'white', groups: ['Темный', 'Зеленый']},
    {code: 'ral7004', title: 'RAL 7004 Сигнальный серый', class: 'ral7004', bgColor: '#9ea0a1', textColor: '', groups: ['Светлый', 'Темный', 'Серый']},
    {code: 'ral9002', title: 'RAL 9002 Светло-серый', class: 'ral9002', bgColor: '#ddded4', textColor: '', groups: ['Светлый', 'Серый']},
    {code: 'ral9004', title: 'RAL 9004 Сигнальный черный', class: 'ral9004', bgColor: '#2e3032', textColor: 'white', groups: ['Темный', 'Серый']},
    {code: 'ral9003', title: 'RAL 9003 Сигнальный белый', class: 'ral9003', bgColor: '#f4f8f4', textColor: '', groups: ['Светлый', 'Серый']},
    {code: 'ral8004', title: 'RAL 8004 Терракот', class: 'ral8004', bgColor: '#8f4e35', textColor: 'white', groups: ['Темный', 'Коричневый']},
    {code: 'ral8017', title: 'RAL 8017 Шоколадно-коричневый', class: 'ral8017', bgColor: '#44322d', textColor: 'white', groups: ['Темный', 'Коричневый']},
    {code: 'bg-1', title: 'Темное дерево', class: 'colorbg bg-1', bgColor: '', textColor: '', groups: ['Рисунок']},
    {code: 'bg-2', title: 'Светлое дерево', class: 'colorbg bg-2', bgColor: '', textColor: '', groups: ['Рисунок']},
    {code: 'bg-3', title: 'Камень природный', class: 'colorbg bg-3', bgColor: '', textColor: '', groups: ['Рисунок']},
    {code: 'bg-4', title: 'Кирпич', class: 'colorbg bg-4', bgColor: '', textColor: '', groups: ['Рисунок']},
    {code: 'bg-5', title: 'Камень песчаник', class: 'colorbg bg-5', bgColor: '', textColor: '', groups: ['Рисунок']},
];